//! Frozen S1 public declarations; unchanged wire tests check their contracts.
const std = @import("std");
const strand = @import("../strand.zig");
const baseline = @embedFile("../corpus/compatibility-s1.json");
test "S2 frozen S1 public manifest compiles" {
    comptime {
        if (!@hasDecl(strand, "core")) @compileError("removed S1 export core");
        if (!@hasDecl(strand, "parseLine")) @compileError("removed S1 export parseLine");
        if (!@hasDecl(strand, "innerParse")) @compileError("removed S1 export innerParse");
        if (!@hasDecl(strand, "ParseOptions")) @compileError("removed S1 export ParseOptions");
        if (!@hasDecl(strand, "Diagnostics")) @compileError("removed S1 export Diagnostics");
        if (!@hasDecl(strand, "DuplicateFields")) @compileError("removed S1 export DuplicateFields");
        if (!@hasDecl(strand, "ParseLineError")) @compileError("removed S1 export ParseLineError");
        if (!@hasDecl(strand, "Line")) @compileError("removed S1 export Line");
        if (!@hasDecl(strand, "RawLine")) @compileError("removed S1 export RawLine");
        if (!@hasDecl(strand, "Format")) @compileError("removed S1 export Format");
        if (!@hasDecl(strand, "Fault")) @compileError("removed S1 export Fault");
        if (!@hasDecl(strand, "separator")) @compileError("removed S1 export separator");
        if (!@hasDecl(strand, "lines")) @compileError("removed S1 export lines");
        if (!@hasDecl(strand, "LineIterator")) @compileError("removed S1 export LineIterator");
        if (!@hasDecl(strand, "LineReader")) @compileError("removed S1 export LineReader");
        if (!@hasDecl(strand, "Reader")) @compileError("removed S1 export Reader");
        if (!@hasDecl(strand, "Writer")) @compileError("removed S1 export Writer");
        if (!@hasDecl(strand, "writeLine")) @compileError("removed S1 export writeLine");
        if (!@hasDecl(strand, "writeValue")) @compileError("removed S1 export writeValue");
        if (!@hasDecl(strand, "writeObjectOpen")) @compileError("removed S1 export writeObjectOpen");
        if (!@hasDecl(strand, "OpenObject")) @compileError("removed S1 export OpenObject");
        if (!@hasDecl(strand, "leadingIntMembers")) @compileError("removed S1 export leadingIntMembers");
        if (!@hasDecl(strand, "IntMembers")) @compileError("removed S1 export IntMembers");
        if (!@hasDecl(strand, "ValueOptions")) @compileError("removed S1 export ValueOptions");
        if (!@hasDecl(strand, "Tail")) @compileError("removed S1 export Tail");
        if (!@hasDecl(strand, "Follower")) @compileError("removed S1 export Follower");
        if (!@hasDecl(strand, "Opener")) @compileError("removed S1 export Opener");
        if (!@hasDecl(strand, "PathOpener")) @compileError("removed S1 export PathOpener");
        if (!@hasDecl(strand, "Identity")) @compileError("removed S1 export Identity");
        if (!@hasDecl(strand, "FileId")) @compileError("removed S1 export FileId");
        if (!@hasDecl(strand, "Versioned")) @compileError("removed S1 export Versioned");
        if (!@hasDecl(strand, "payloadOf")) @compileError("removed S1 export payloadOf");
        if (!@hasDecl(strand, "Raw")) @compileError("removed S1 export Raw");
        if (!@hasDecl(strand, "copyOwned")) @compileError("removed S1 export copyOwned");
        if (!@hasDecl(strand, "freeOwned")) @compileError("removed S1 export freeOwned");
        if (!@hasDecl(strand, "kindOf")) @compileError("removed S1 export kindOf");
        if (!@hasDecl(strand, "tagOf")) @compileError("removed S1 export tagOf");
        if (!@hasDecl(strand, "memberOf")) @compileError("removed S1 export memberOf");
        if (!@hasDecl(strand, "memberStringOf")) @compileError("removed S1 export memberStringOf");
        if (!@hasDecl(strand, "indexOfControl")) @compileError("removed S1 export indexOfControl");
        if (!@hasDecl(strand, "Reached")) @compileError("removed S1 export Reached");
        std.testing.refAllDecls(strand);
        std.testing.refAllDecls(strand.Raw);
        std.testing.refAllDecls(strand.Reader(struct {}));
        std.testing.refAllDecls(strand.Writer(struct {}));
        std.testing.refAllDecls(strand.Tail(struct {}));
        std.testing.refAllDecls(strand.Follower(struct {}));
        std.testing.refAllDecls(strand.LineReader);
        std.testing.refAllDecls(strand.OpenObject);
        std.testing.refAllDecls(strand.Opener);
        std.testing.refAllDecls(strand.PathOpener);
        std.testing.refAllDecls(strand.Identity);
    }
    try std.testing.expect(baseline.len > 0);
}
