#!/usr/bin/env bash
#
# zjsonl — the generated blocks in README.md, regenerated and compared.
#
# A block between `<!-- BEGIN GENERATED <command> -->` and
# `<!-- END GENERATED -->` must equal that command's output. The marker names
# the generator, so a reader can rerun it, and CI fails on a block that has
# drifted from the code it was taken from.
#
# Usage:
#   ci/check-readme.sh           # compare, fail on any difference
#   ci/check-readme.sh --write   # rewrite the blocks from their generators

set -uo pipefail
cd "$(dirname "$0")/.."

exec python3 - "${1:-}" <<'PY'
import difflib
import pathlib
import re
import subprocess
import sys

write = sys.argv[1] == "--write"
block = re.compile(
    r"(?P<open><!-- BEGIN GENERATED (?P<cmd>[^>]+?) -->\n)"
    r"(?P<body>.*?)"
    r"(?P<close><!-- END GENERATED -->)",
    re.S,
)
failures = 0

for doc in sorted(pathlib.Path(".").glob("*.md")):
    text = doc.read_text(encoding="utf-8")
    out = []
    end = 0
    for m in block.finditer(text):
        cmd = m.group("cmd").strip()
        run = subprocess.run(["bash", "-c", cmd], capture_output=True, text=True)
        if run.returncode != 0:
            print("%s: generator failed: %s\n%s" % (doc, cmd, run.stderr.strip()))
            failures += 1
            continue
        want = run.stdout.replace("\r\n", "\n")
        if not want.endswith("\n"):
            want += "\n"
        have = m.group("body")
        if have != want:
            failures += 1
            print("%s: the block generated by `%s` is stale:" % (doc, cmd))
            for line in difflib.unified_diff(
                have.splitlines(True), want.splitlines(True),
                fromfile="in the document", tofile=cmd, n=1,
            ):
                print("  " + line.rstrip("\n"))
        out.append(text[end:m.start()])
        out.append(m.group("open") + want + m.group("close"))
        end = m.end()
    if write and out:
        out.append(text[end:])
        doc.write_text("".join(out), encoding="utf-8")

if write:
    sys.exit(0)
sys.exit(1 if failures else 0)
PY
